# Generated by Django 6.0.7 on 2026-07-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='email_on_assignment',
            field=models.BooleanField(default=True),
        ),
    ]
