# Generated by Django 6.0.7 on 2026-07-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notificationpreference_email_on_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='email_on_license_expiry',
            field=models.BooleanField(default=True),
        ),
    ]
