# Generated by Django 6.0.7 on 2026-08-09 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notificationpreference_email_on_license_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_agent_self_assign', models.BooleanField(default=False)),
                ('allow_agent_reassign', models.BooleanField(default=False)),
                ('allow_agent_edit_after_close', models.BooleanField(default=False)),
                ('allow_agent_edit_customers', models.BooleanField(default=False)),
                ('allow_agent_create_customers', models.BooleanField(default=False)),
                ('allow_agent_delete', models.BooleanField(default=False)),
                ('allow_agent_link_customer', models.BooleanField(default=False)),
                ('allow_agent_manage_kb', models.BooleanField(default=False)),
                ('allow_agent_assign_projects', models.BooleanField(default=False)),
                ('allow_agent_unassign_projects', models.BooleanField(default=False)),
                ('allow_agent_assign_tasks', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='staff_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.staffrole'),
        ),
    ]
