# Generated by Django 6.0.7 on 2026-08-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_staffrole_user_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='allow_agent_view_reports',
            field=models.BooleanField(default=False),
        ),
    ]
