# Generated by Django 6.0.7 on 2026-08-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_staffrole_allow_agent_view_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='allow_agent_view_customers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='allow_agent_view_projects',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='allow_agent_view_tickets',
            field=models.BooleanField(default=True),
        ),
    ]
