# Generated by Django 6.0.7 on 2026-08-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_staffrole_allow_agent_view_customers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='email_on_todo_reminder',
            field=models.BooleanField(default=True),
        ),
    ]
