# Generated by Django 6.0.7 on 2026-09-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_notificationpreference_email_on_todo_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='withheld_ticket_columns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='hidden_ticket_columns',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
