# Generated by Django 6.0.7 on 2026-09-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customer_software_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='allow_agent_customize_columns',
            field=models.BooleanField(default=False),
        ),
    ]
