# Generated by Django 6.0.7 on 2026-09-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customize_columns_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=10, null=True),
        ),
    ]
