# Generated by Django 6.0.7 on 2026-09-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customer_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_set_ticket_priority',
            field=models.BooleanField(default=True),
        ),
    ]
