# Generated by Django 6.0.7 on 2026-07-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('general', 'General'), ('new_ticket', 'New ticket')], default='general', max_length=20),
        ),
    ]
