# Generated by Django 6.0.7 on 2026-09-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_assigned_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('general', 'General'), ('new_ticket', 'New ticket'), ('license_expiry', 'License expiry'), ('assigned', 'Ticket assigned'), ('collaborator_added', 'Added as collaborator')], default='general', max_length=20),
        ),
    ]
