# Generated by Django 6.0.7 on 2026-09-15 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_collaborator_added_notification_kind'),
        ('projects', '0019_todo_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='todo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.todoitem'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('general', 'General'), ('new_ticket', 'New ticket'), ('license_expiry', 'License expiry'), ('assigned', 'Ticket assigned'), ('collaborator_added', 'Added as collaborator'), ('todo_assigned', 'To-do assigned')], default='general', max_length=20),
        ),
    ]
