# Generated by Django 6.0.7 on 2026-08-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
