# Generated by Django 6.0.7 on 2026-08-05 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notificationpreference_email_on_license_expiry'),
        ('projects', '0008_project_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='accounts.customerbranch'),
        ),
    ]
