# Generated by Django 6.0.7 on 2026-08-13 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_todo_datetimes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['is_private', 'created_by'], name='projects_to_is_priv_900e7d_idx'),
        ),
    ]
