# Generated by Django 6.0.7 on 2026-08-13 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_todoitem_is_private_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_private', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='todo_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='todoitem',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='projects.todofolder'),
        ),
        migrations.AddConstraint(
            model_name='todofolder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_private', False)), fields=('name',), name='unique_shared_todo_folder_name'),
        ),
        migrations.AddConstraint(
            model_name='todofolder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_private', True)), fields=('name', 'created_by'), name='unique_private_todo_folder_name_per_user'),
        ),
    ]
