# Generated by Django 6.0.7 on 2026-08-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_todoitem_remind_at_todoitem_reminder_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='remind_offset_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
