# Generated by Django 6.0.7 on 2026-07-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_agent_self_assign', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ticket settings',
                'verbose_name_plural': 'Ticket settings',
            },
        ),
    ]
