# Generated by Django 6.0.7 on 2026-07-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketactivity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('priority_changed', 'Priority changed'), ('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('commented', 'Commented'), ('attachment_added', 'Attachment added'), ('deadline_set', 'Deadline set')], max_length=20),
        ),
    ]
