# Generated by Django 6.0.7 on 2026-07-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_due_at_alter_ticketactivity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsettings',
            name='allow_agent_reassign',
            field=models.BooleanField(default=False),
        ),
    ]
