# Generated by Django 6.0.7 on 2026-07-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_category_options_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
    ]
