# Generated by Django 6.0.7 on 2026-07-16 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_category_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='tickets_collaborating', to=settings.AUTH_USER_MODEL),
        ),
    ]
