# Generated by Django 6.0.7 on 2026-07-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_hold_reason_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsettings',
            name='allow_edit_after_close',
            field=models.BooleanField(default=False),
        ),
    ]
