# Generated by Django 6.0.7 on 2026-07-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='guest_company',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
