# Generated by Django 6.0.7 on 2026-07-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_ticket_guest_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketactivity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('priority_changed', 'Priority changed'), ('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('commented', 'Commented'), ('attachment_added', 'Attachment added'), ('deadline_set', 'Deadline set'), ('customer_linked', 'Customer linked')], max_length=20),
        ),
    ]
