# Generated by Django 6.0.7 on 2026-07-21 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customerbranch'),
        ('tickets', '0017_ticket_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='accounts.customerbranch'),
        ),
    ]
