# Generated by Django 6.0.7 on 2026-07-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_ticket_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsettings',
            name='allow_agent_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketsettings',
            name='allow_agent_edit_customers',
            field=models.BooleanField(default=False),
        ),
    ]
