# Generated by Django 6.0.7 on 2026-07-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_ticketsettings_allow_agent_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsettings',
            name='allow_agent_link_customer',
            field=models.BooleanField(default=False),
        ),
    ]
