# Generated by Django 6.0.7 on 2026-07-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_ticketsettings_allow_agent_link_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketsettings',
            old_name='allow_edit_after_close',
            new_name='allow_agent_edit_after_close',
        ),
    ]
