# Generated by Django 6.0.7 on 2026-07-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_rename_allow_edit_after_close_ticketsettings_allow_agent_edit_after_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
