# Generated by Django 6.0.7 on 2026-07-26 09:29

from django.db import migrations
from django.db.models import F


def backfill(apps, schema_editor):
    """Repair completion timestamps for tickets closed before closed_at existed.

    The old status logic cleared resolved_at whenever a ticket left the resolved
    state, so historical closed tickets lost their resolution time and carry no
    closed_at. Approximate both from updated_at (the best proxy available) so
    resolution-time reporting counts them again."""
    Ticket = apps.get_model('tickets', 'Ticket')

    # Closed tickets: stamp closed_at, and resolved_at if it was wiped.
    Ticket.objects.filter(status='closed', closed_at__isnull=True).update(
        closed_at=F('updated_at')
    )
    Ticket.objects.filter(status='closed', resolved_at__isnull=True).update(
        resolved_at=F('updated_at')
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_ticket_closed_at'),
    ]

    operations = [
        migrations.RunPython(backfill, noop),
    ]
