# Generated by Django 6.0.7 on 2026-07-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_backfill_completion_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rating_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rating_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rating_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='ticketactivity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('priority_changed', 'Priority changed'), ('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('commented', 'Commented'), ('attachment_added', 'Attachment added'), ('deadline_set', 'Deadline set'), ('customer_linked', 'Customer linked'), ('rated', 'Rated')], max_length=20),
        ),
    ]
