# Generated by Django 6.0.7 on 2026-07-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_article_ticket_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsettings',
            name='allow_agent_manage_kb',
            field=models.BooleanField(default=False),
        ),
    ]
