# Generated by Django 6.0.7 on 2026-08-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_ticketphase'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='guest_branch',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
