# Generated by Django 6.0.7 on 2026-08-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_ticket_guest_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsettings',
            name='allow_agent_assign_projects',
            field=models.BooleanField(default=False),
        ),
    ]
