# Generated by Django 6.0.7 on 2026-08-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_agent_assign_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsettings',
            name='allow_agent_unassign_projects',
            field=models.BooleanField(default=False),
        ),
    ]
