# Generated by Django 6.0.7 on 2026-08-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_agent_assign_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsettings',
            name='allow_agent_create_customers',
            field=models.BooleanField(default=False),
        ),
    ]
