# Generated by Django 6.0.7 on 2026-08-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_agent_create_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsettings',
            name='allow_agent_view_reports',
            field=models.BooleanField(default=False),
        ),
    ]
