# Generated by Django 6.0.7 on 2026-08-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_ticketsettings_allow_agent_view_customers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category_priority_override',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=10, null=True),
        ),
    ]
