# Generated by Django 6.0.7 on 2026-09-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0036_ticket_category_priority_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsettings',
            name='withheld_ticket_columns',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
