# Generated by Django 6.0.7 on 2026-09-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0037_ticket_column_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsettings',
            name='allow_agent_customize_columns',
            field=models.BooleanField(default=False),
        ),
    ]
